module.exports = [
	{"name": "accuracy",      "shortName": "acc", "focusList": ["Bows","Gunnery","Pistols","Rifles","Throwing"]                                                                                                                                           },
	{"name": "communication", "shortName": "com", "focusList": ["Bargaining","Deception","Disguise","Etiquette","Expression","Gambling","Investigation","Leadership","Performing","Persuasion","Seduction"]                                               },
	{"name": "constitution",  "shortName": "con", "focusList": ["Running","Stamina","Swimming","Tolerance"]                                                                                                                                               },
	{"name": "dexterity",     "shortName": "dex", "focusList": ["Acrobatics","Crafting","Driving","Initiative","Piloting","Sleight of Hand","Stealth"]                                                                                                    },
	{"name": "fighting",      "shortName": "fit", "focusList": ["Brawling","Grappling","Heavy Weapons","Light Weapons"]                                                                                                                                   },
	{"name": "intelligence",  "shortName": "int", "focusList": ["Art","Business","Cryptography","Current Afairs","Demolitions","Engineering","Evaluation","History","Law","Medicine","Navigation","Research","Science","Security","Tactics","Technology"] },
	{"name": "perception",    "shortName": "per", "focusList": ["Empathy","Hearing","Intuition","Searching","Seeing","Smelling","Survival","Tasting","Touching","Tracking"]                                                                               },
	{"name": "strength",      "shortName": "str", "focusList": ["Climbing","Intimidation","Jumping","Might"]                                                                                                                                              },
	{"name": "willpower",     "shortName": "wil", "focusList": ["Courage","Faith","Self-Discipline"]                                                                                                                                                      }
]
